# Hyperparameter Grid for Bayesian Optimization
# Defines the search space for tuning GiBERTino's hyperparameters.

script: train.py  # The training script to execute
config_file: config.yaml  # The base configuration file used for training

attr_keys:
  model:
    hidden_channels: 16, 32, 64, 128
    num_layers: 2, 3, 4, 5
  data:
    batch_size: 16, 32, 64