# Hyperparameter Grid for Bayesian Optimization
# Defines the search space for tuning GiBERTino's hyperparameters.

script: train.py  # The training script to execute
config_file: config.yaml  # The base configuration file used for training

attr_keys:
  model:
    gnn_model: GCN
    hidden_channels: 64, 128, 256, 512, 1024
    num_layers: 32, 64, 128
    lr: 1e-5, 1e-2
  data:
    batch_size: 16, 32, 64